name: 'Test Run'
run-name: 'Deleting all record in curriculum architect table for ${{ inputs.environment }}::${{ inputs.aws_region }}'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Environment
        options:
          - development
          - staging
          - production # woah! don't do this!

permissions:
  id-token: write
  contents: read

jobs:
  google-chat-action:
    name: Google Chat GitHub Action Pt1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Echo
        id: echo
        run: |
          echo "Hello, this is a test run for environment ${{ inputs.environment }} in region ${{ inputs.aws_region }}"
          exit 1

  run-google-chat:
    needs: [google-chat-action]
    name: Google Chat GitHub Action Pt2
    runs-on: ubuntu-latest
    if: ${{ always() }} # Ensure this job runs even if the previous one fails

    steps:
      - name: Fail if previous jobs failed
        if: ${{ needs.google-chat-action.result != 'success' }}
        run: |
          echo "One or more previous jobs failed."
          exit 1
      - name: Notify Google Chat
        if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{secrets.GOOGLE_CHAT_WEBHOOK_URL}}'
          jobStatus: ${{ job.status }}
          imageType: 'SQUARE'
          title: Production Deployment Notification 🔔
          subtitle: 'Deployment to ${{ inputs.environment }} was ${{ job.status }}'
          imageUrl: ${{ job.status == 'success' && 'https://media1.tenor.com/m/ZQdH9YACdxQAAAAC/ip-meme.gif' || 'https://i.pinimg.com/736x/df/81/97/df8197b453631724fef58d06ad4133f3.jpg' }}
          
